edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]

[plugin]  
prepend_previewers = [  
	# duckdb (csv, json et similia)
	{ url = "*.csv", run = "duckdb" },  
	{ url = "*.tsv", run = "duckdb" },  
	{ url = "*.json", run = "duckdb" },  
	{ url = "*.parquet", run = "duckdb" },  
	{ url = "*.txt", run = "duckdb" },  
	{ url = "*.xlsx", run = "duckdb" },  
	{ url = "*.db", run = "duckdb" },
	{ url = "*.duckdb", run = "duckdb" },
	
	# Eza (folder structure)
	{ url = "*/", run = "eza-preview"},

	# Removing it allow image preview to work. Check why
    # Mediainfo (Image, audio etc)
    # { mime = "{audio,video,image}/*", run = "mediainfo"},
    # { mime = "application/subrip", run = "mediainfo" },

]

prepend_preloaders = [  
	# duckdb (csv, json et similia)
	{ url = "*.csv", run = "duckdb", multi = false },  
	{ url = "*.tsv", run = "duckdb", multi = false },  
	{ url = "*.json", run = "duckdb", multi = false },  
	{ url = "*.parquet", run = "duckdb", multi = false },
	{ url = "*.txt", run = "duckdb", multi = false },  
	{ url = "*.xlsx", run = "duckdb", multi = false },
	
	# Removing it allow image preview to work. Check why
	# Mediainfo (Image, audio etc)
	# { mime = "{audio,video,image}/*", run = "mediainfo" },
	# { mime = "application/subrip", run = "mediainfo" },
]

# Get some metadata to display near the elemen in yazy
# Group specify if it is applied to file or folder
prepend_fetchers = [
	{ id = "git", url = "*" , run = "git", group = "0" },
	{ id = "git", url = "*/", run = "git", group = "1" }
]

